### PR TITLE
Fix black screen

### PR DESCRIPTION
**Pull request by mkryuchkov**
Newer versions of platform kit cause black screen on start.
KNOMI v2 has this issue, not sure bout v1.

Alternative option is to adopt source code to newer kits, but I don't have any debug abilities like hw dev-kit or esp32 debug knowledge.

This PR is just about to make current version working.

### CODE REVIEW

**Comment by bodydropped72** [comment]
came across this as my knomi2 screen went black. how do i get into the device to change that line. Light on back of device but i dont know how to get into it.

**Comment by mkryuchkov** [comment]
@bodydropped72 I described the way here https://github.com/DiverOfDark/KNOMI/issues/239#issuecomment-2114596078

So you can revert your KNOMI to precompiled version (It also possible to use DiverOfDark's re-flasher and choose revert to stock option) and then flash your build, or just flash yours with fix on top.
KNOMI2 has esp32s3 onboard so if device has red light, connected via usb and identified by pc it should be flashed. I described nuances in the comment by link.

**Comment by bodydropped72** [comment]
i have looked at the link you sent me. the knomi2 when plugged into my
computer via usb is not recognized by it (looking in device manager).

**Comment by mkryuchkov** [comment]
@bodydropped72 
Check if new COM port appeared after plug in (it's okay if it does; this port is need for flashing);
If not you may install driver from <https://www.wch-ic.com/downloads/CH341SER_EXE.html> and check again.

Generally, you should be able to flash knomi the same way you flashed black-screen FW. Try to flash precompiled first with sectors set as I described (0x0000 for bootloader).

**Comment by bodydropped72** [comment]
This is my com ports with knomi plugged in.Robby Mendel On Jun 13, 2024, at 8:31 AM, Mikhail Kryuchkov ***@***.***> wrote:﻿
@bodydropped72
Check if new COM port appeared after plug in (it's okay if it does; this port is need for flashing);
If not you may install driver from https://www.wch-ic.com/downloads/CH341SER_EXE.html and check again.
Generally, you should be able to flash knomi the same way you flashed black-screen FW. Try to flash precompiled first with sectors set as I described (0x0000 for bootloader).

**Comment by trevjonez** [comment]
Root cause of the black screen, for anyone who wants to unpin the platform.

The pin works, but it treats a symptom. The actual fault is TFT_eSPI's SPI port
selection on the ESP32-S3, and one `#define` fixes it.

### What happens

With `platform = espressif32` newer than 6.4.0, the KNOMI2 panics on boot before
the display is ever initialised:

```
Guru Meditation Error: Core 1 panic'ed (StoreProhibited)
EXCCAUSE: 0x0000001d   EXCVADDR: 0x00000010
```

Symbolized:

```
TFT_eSPI::begin_tft_write()              TFT_eSPI.cpp:81
  (inlined by) TFT_eSPI::writecommand()  TFT_eSPI.cpp:982
TFT_eSPI::init()                         TFT_eSPI.cpp:692
TFT_eSPI::begin()                        TFT_eSPI.cpp:603
lvgl_hal_init()                          src/lvgl_hal.cpp:115
lvgl_ui_task()                           src/lvgl_usr.cpp:49
```

### Why

In `Processors/TFT_eSPI_ESP32_S3.c`, when neither `USE_HSPI_PORT` nor
`USE_FSPI_PORT` is defined, the non-classic-ESP32 branch falls through to:

```c
#else // use FSPI port
  SPIClass& spi = SPI;
#endif
```

i.e. the global Arduino `SPI` object. On newer Arduino-ESP32 cores that bus does
not start: `spiStartBus()` returns NULL, `SPIClass::_spi` stays NULL, and the
first `writecommand()` inside `TFT_eSPI::init()` dereferences it. `EXCVADDR
0x10` is that null pointer plus a field offset. The panel is never initialised,
so the screen stays black.

### Fix

Give TFT_eSPI its own SPI port -- one line in `src/tft_setup.h`:

```c
#define USE_HSPI_PORT
```

### Tested

On KNOMI2 hardware (ESP32-S3 R8, 8MB PSRAM), with `platform =
espressif32@6.13.0` (Arduino-ESP32 2.0.17):

| TFT_eSPI | without `USE_HSPI_PORT` | with it |
|---|---|---|
| 2.5.0 (the version pinned here) | panic as above | boots, display draws |
| 2.5.43 | panic as above | boots, display draws |

Display, Wi-Fi, mDNS and Moonraker polling all work. No TFT_eSPI bump is needed
-- 2.5.0 contains the same fallback, so the `#define` alone is sufficient to
unpin the platform.

### One caveat: a platform bump cannot be delivered over OTA

Worth flagging separately, because it is easy to brick a device finding out.
`bootloader.bin` differs between platform releases (15,088 bytes on 6.4.0 vs
15,104 on 6.13.0; `partitions.bin` is unchanged). AsyncElegantOTA's `U_FLASH`
path writes only the app OTA slot -- it cannot write offset `0x0`.

So OTA-ing a newer-platform build leaves the new app running under the old
bootloader. The result is a device with no display, no Wi-Fi, no mDNS and no AP
fallback, recoverable only over USB. A full USB flash of bootloader +
partitions + boot_app0 + app works fine:

```
esptool.py --chip esp32s3 --port <port> --baud 460800 \
  write_flash -z --flash_mode keep --flash_freq keep --flash_size keep \
  0x0 bootloader.bin 0x8000 partitions.bin 0xe000 boot_app0.bin 0x10000 firmware.bin
```

(The KNOMI2 bridges UART0 through a CH340, so it enumerates as `/dev/ttyUSB*`
and esptool's RTS auto-reset works without touching a BOOT button.)

**Pull request merged**
