### PR TITLE
added interface to macro _KNOMI_STATUS

### PR DESCRIPTION
**Pull request by Surion79**
Due to the errors with G28 and homing override, I created this PR. This PR consists of two parts:
- Changes in source code (main.cpp)
- Functional documentation (described in this PR text)

I added a new part of looking through the API calls for a macro called `_KNOMI_STATUS` instead of `G28` and `BED_MESH_CALIBRATE`.

It is NOT backwards compatible with the "original" version!
The new `_KNOMI_STATUS` macro would need to look like this

```
[gcode_macro _KNOMI_STATUS] 
variable_homing: False  
variable_probing: False  
gcode:  
``` 

with this it is now generally possible to set the status whereever it is needed.
Therefore just add the following lines where it is appropriate:

```
SET_GCODE_VARIABLE MACRO=_KNOMI_STATUS VARIABLE=homing VALUE=True
SET_GCODE_VARIABLE MACRO=_KNOMI_STATUS VARIABLE=homing VALUE=False
```
```
SET_GCODE_VARIABLE MACRO=_KNOMI_STATUS VARIABLE=probing VALUE=True
SET_GCODE_VARIABLE MACRO=_KNOMI_STATUS VARIABLE=probing VALUE=False
```

if you use a homing_override you can add it like this: (this is just a technical example!)
```
SET_GCODE_VARIABLE MACRO=_KNOMI_STATUS VARIABLE=homing VALUE=True
G28
SET_GCODE_VARIABLE MACRO=_KNOMI_STATUS VARIABLE=homing VALUE=False
```

This does not require a G28 override which is not possible when using homing_override.

My KNOMI display ships in a couple days, so i wasn't able to test this with a KNOMI display.

### CODE REVIEW

**Comment by Cyondil** [comment]
I have the Knomi and tested your PR and it doesn't seem to work at all for either homing or probing

First, the variables of true and false need to have the first letter capitalized (True/False) or else Klipper throws up an error.

For homing, still issues with it not updating the status on the Knomi even with the above fix.  Seems like G28 is going to be tougher nut to crack.

For probing, this also does not seem to work.  I use KAMP so I was able to get it to work by adding the variable under the KAMP cfg and adding the below lines to the beginning and end of the KAMP bed mesh macro.  When I pointed them to the _KNOMI_STATUS it also did not reflect correctly.
SET_GCODE_VARIABLE MACRO=BED_MESH_CALIBRATE VARIABLE=probing VALUE=True
SET_GCODE_VARIABLE MACRO=BED_MESH_CALIBRATE VARIABLE=probing VALUE=False

Not much of someone who digs into code. but seems to me that there is something specifically looking for the combo of BED_MESH_CALIBRATE/G28 and the variable switch.

**Comment by Surion79** [comment]
> I have the Knomi and tested your PR and it doesn't seem to work at all for either homing or probing
> 
> First, the variables of true and false need to have the first letter capitalized (True/False) or else Klipper throws up an error.
> 
> For homing, still issues with it not updating the status on the Knomi even with the above fix. Seems like G28 is going to be tougher nut to crack.
> 
> For probing, this also does not seem to work. I use KAMP so I was able to get it to work by adding the variable under the KAMP cfg and adding the below lines to the beginning and end of the KAMP bed mesh macro. When I pointed them to the _KNOMI_STATUS it also did not reflect correctly. SET_GCODE_VARIABLE MACRO=BED_MESH_CALIBRATE VARIABLE=probing VALUE=True SET_GCODE_VARIABLE MACRO=BED_MESH_CALIBRATE VARIABLE=probing VALUE=False
> 
> Not much of someone who digs into code. but seems to me that there is something specifically looking for the combo of BED_MESH_CALIBRATE/G28 and the variable switch.

Thanks, i updated the documentation.
Although i did not grasp your other issue. Can you give a full example of your code where you put it? You commented code, which is not part of my documentation

**Comment by Cyondil** [comment]
Sure!  I've been spending some time on this today, so probably speaking a bit in riddles.  I am using KAMP (Klipper Adaptive Meshing and Purging) for my meshing.  KAMP includes an Adaptive_Mesh.cfg and renames the existing BED_MESH_CALIBRATE and then calls it later in the macro.

In this macro I can add the following:
`SET_GCODE_VARIABLE MACRO=BED_MESH_CALIBRATE VARIABLE=probing VALUE=True
...rest of macro code...
SET_GCODE_VARIABLE MACRO=BED_MESH_CALIBRATE VARIABLE=probing VALUE=False`

to the beginning and  end of the macro and have probing show up correctly on Knomi. So a known working configuration for me but still missing the homing, so I wanted to try your solution.

I created the _KNOMI_STATUS macro as described above and then replaced the two lines in my Adaptive_Mesh.cfg with your lines 
`SET_GCODE_VARIABLE MACRO=_KNOMI_STATUS VARIABLE=probing VALUE=True
...rest of macro code...
SET_GCODE_VARIABLE MACRO=_KNOMI_STATUS VARIABLE=probing VALUE=False`

Probing status on the Knomi does not display. When I change it back to my first lines, it works again.  Hopefully this is more clear now and makes sense with what I am trying to say. 

In addition, to back this up, I was able to get my homing to work on the display if I tweaked things to use G28 and change the variable using:
`SET_GCODE_VARIABLE MACRO=G28 VARIABLE=probing VALUE=True
...rest of macro code...
SET_GCODE_VARIABLE MACRO=G28=probing VALUE=False`

BUT, I did have to monkey with things a bit for my testing to work correctly as I have a sensorless homing and use homing override for it.  While I got it to work and display on Knomi, it also broke my individual axis homing.  

Since I had something that worked, I also tried to substitute the _KNOMI_STATUS variable changes into what I got working.  Same thing, not working.

Using these tests, but my suspicion is that source code it's looking specifically for the combination of the BED_MESH_CALIBRATE/G28 and variable status combination to work.

**Comment by Surion79** [comment]
> Editing this comment because I missed the fact you made changes to the codebase itself. Just one of those days here and I realized now what changes you made. Retracting my previous comments as it looks as if you have everything already covered in your code changes. No further comments. Only thing that would be nice is if BTT would release a guide to update the firmware more easily!

have you tried to update the firmware with this fix? does it work? my display takes some time until it arrives

**Comment by littleferris** [comment]
Trying out this code, and when I add the commands you listed to my homing macro, it doesnt update the screen, but if I just do it in the console it does.

**Comment by Surion79** [comment]
> Thank you for this, it seems like the homing one works, but the probing does not. Just testing in the console.

Have you compiled the firmware and upgraded the knomi display with it?

**Comment by Cyondil** [comment]
> > Editing this comment because I missed the fact you made changes to the codebase itself. Just one of those days here and I realized now what changes you made. Retracting my previous comments as it looks as if you have everything already covered in your code changes. No further comments. Only thing that would be nice is if BTT would release a guide to update the firmware more easily!
> 
> have you tried to update the firmware with this fix? does it work? my display takes some time until it arrives

Yeah that's the piece I was missing.  I compiled the new firmware with the fix but haven't tried installing it yet.  Got tied up with a few things and I'm hoping to get back to it within the next day or so and will report back!

**Review by Cyondil — CHANGES_REQUESTED** [review]
I tested the code and it did not work.  After digging through, I think I see the issue.  You originally created a new httpswitch (5) that referenced the new _KNOMI_SRATUS macro.  

After this recent change where you removed the httpswitch = 5 and then changed the httpswitch =4 and httpswitch = 3 to focus on the _KNOMI_STATUS macro, it broke.  It looks like now what happens, in lines 986 and 988, it's still looking for the G0028 and BED_MESH_CALIBRATE to trigger these switches.  I edited the code to replace G0028 and BED_MESH_CALIBRATE with _KNOMI_STATUS and then compiled and uploaded the firmware.  Both Homing and Probing now show correctly on the display.

Since httpswitch =5 is no longer required the lines 989 and 990 can now be removed as well.

Once I made these changes, compiled and uploaded the firmware, I'm no able to successfully see that Knomi changes for both homing AND probing! Now I just need to figure out how I can change the colors from red to blue.  :)

Screenshot attached for reference.
Screenshot 2023-05-20 112755

**Comment by Surion79** [comment]
@Cyondil Thanks! Unfortunately i have not my KNOMI yet, so I couldn't test the changes. 
I updated the file accordingly, so it should be now working. As replacement

**Review by Surion79 — COMMENTED** [review]
i removed http switch 5, so it should not be added and kept as in original. other stuff i changed accordingly. should work now like this

**Review by Cyondil — APPROVED** [review]
Changes look good and have been tested as working with the new macro.  No recursive issues with homing.

**Comment by Cyondil** [comment]
> hello, i want to test this also. Please can you tell me how to compile and how to load this firmware onto my Knomi. i have tried with ESP-Flasher, but no success. Maybe also the compiled firmware isn´t ok. So I need your help please.

Easiest is to use VSCode with the Platform.io extension.  With the Knomi connected to your computer in boot mode (hold the boot button while plugging it in and release once powered on), you build and then upload using the Platform.io extension.

**Comment by Paliomalakas** [comment]
which files sould we upload?

**Comment by SrgntBallistic** [comment]
BTT has instructions on how to compile here:
https://bigtreetech.github.io/docs/KNOMI.html#customize-ui

**Comment by Paliomalakas** [comment]
Thank you very much

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SrgntBallistic** [comment]
I was able to get this working.

I am currently using the G28 override as I don't have a homing_override.

**Comment by appleimperio** [comment]
This works great. Thank you!

**Comment by acosano** [comment]
Hi. I run into the same problem. I have a G28 and Homing override and would like to implement your solution. How  to get your branch as I can'tfigure it out. Thanks in advance

**Comment by appleimperio** [comment]
@acosano At the top of this page click on from Surion79:Knomi_Status_Macro. that will take you to the branch
Screenshot 2023-07-02 at 8 32 08 AM

**Comment by acosano** [comment]
So easy. Thanks for that. I will  try it  this morning.

**Comment by 3DMat** [comment]
solved by changing the source code because the package you download still uses the old configuration even if you update the knomi with vscode MASTER FILE NOT UPDATED WITH THE VERSION YOU WRITE

**Comment by ah-banny** [comment]
@Surion79 and @Cyondil 

thank you very much for your work. 
It worked very well on my Voron2.4. now the [quad_gantry_level] doesn't work yet. 
But hopefully I can still do that ;)

**Comment by Ybalrid** [comment]
Hey, I like this idea!

Something like this may solve the configuration I and another user are experiencing with KAMP and BED_MESH_CALIBRATE (see issue #26)

**Comment by BoothyBoothy** [comment]
Hi Surion79, many thanks for all your hard work on this. I have not tried this on any of my V2s because they now have tap. It does work a treat on my recent Minion upgrade with a Klicky Probe attached. However, for some reason the Knomi finish print macro (usually a green tick icon) does not seem to present itself when the print finishes? Any thoughts?

Thanks again for all your efforts. Best wishes Boothy

**Review by TheSin- — APPROVED** [review]
Why isn't the accepted yet?  This is a much cleaner way over all!

**Comment by bigtreetech** [comment]
Thank you very much for your PR.
Inspired by this PR, the latest version of firmware has been implemented using this method.
https://github.com/bigtreetech/KNOMI/tree/firmware
https://github.com/bigtreetech/KNOMI/blob/master/KNOMI.cfg

**Pull request closed without merging**
